#!/bin/bash
# Quick QR Code Test Generator for GreenMate Box

# This script helps create test QR codes for mobile app testing

echo "🚀 GreenMate Box - QR Code Test Generator"
echo "=========================================="
echo ""
echo "QR Code Format Options:"
echo ""
echo "1️⃣  Simple Number Format:"
echo "   Content: 50"
echo "   Generates 50 Eco points"
echo ""
echo "2️⃣  JSON Format:"
echo "   Content: {\"points\":75,\"machineId\":\"CS1\"}"
echo "   Generates 75 Eco points from machine CS1"
echo ""
echo "📱 To Generate QR Codes:"
echo "   1. Visit: https://www.qr-code-generator.com/"
echo "   2. Select 'Text' mode"
echo "   3. Paste one of the formats above"
echo "   4. Download the QR image"
echo "   5. Print or display on screen for scanning"
echo ""
echo "🔍 Testing on Mobile:"
echo "   1. Tap 'Bắt đầu quét' button in Scan tab"
echo "   2. Allow camera permission"
echo "   3. Point at QR code"
echo "   4. App auto-detects and adds points"
echo ""
echo "Test Values:"
echo "  - 50 points (small transaction)"
echo "  - 100 points (medium transaction)"
echo "  - 250 points (large transaction)"
echo "  - 500 points (bonus batch)"
echo ""
echo "✅ Success Response:"
echo "  +{points} ĐIỂM THƯỞNG"
echo "  + CO₂ saved calculated"
echo "  + Transaction logged in Wallet History"
echo ""
